server:
  port: 8085
eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: api-gateway
 cloud:
    gateway:
      routes:
      - id: product-service
        uri: http://localhost:8083/
        predicates:
        - Path=/product/**
      - id: customer-service
        uri: http://localhost:8082/
        predicates:
        - Path=/customer/**

